In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import pandas as pd
import numpy as np
# 시그모이드 함수 expit() 사용을 위해 scipy.special 불러오기
from scipy.special import expit

In [3]:
headings = ['sepal length (cm)',
           'sepal width (cm)',
           'petal length (cm)',
           'petal width (cm)',
           'target']
irisdf = pd.read_csv("iris.data", names=headings)
irisdf

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

In [4]:
irisdf['target'] = irisdf['target'].map({ "Iris-setosa": 0, "Iris-versicolor": 1, "Iris-virginica": 2})
irisdf

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [5]:
iris_test = irisdf.sample(frac=0.2, random_state=3)
len(iris_test)

30

In [6]:
iris_train = irisdf.drop(irisdf.index[iris_test.index])
len(iris_train)

120

In [7]:
iris_test.to_csv("iris_test.csv")

In [8]:
iris_train.to_csv("iris_train.csv")

In [9]:
testdf = pd.read_csv("iris_test.csv")
testdf

,Unnamed: 0,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,47,4.6,3.2,1.4,0.2,0
1,3,4.6,3.1,1.5,0.2,0
2,31,5.4,3.4,1.5,0.4,0
3,25,5.0,3.0,1.6,0.2,0
4,15,5.7,4.4,1.5,0.4,0
5,118,7.7,2.6,6.9,2.3,2
6,89,5.5,2.5,4.0,1.3,1
7,6,4.6,3.4,1.4,0.3,0
8,103,6.3,2.9,5.6,1.8,2
9,65,6.7,3.1,4.4,1.4,1
10,88,5.6,3.0,4.1,1.3,1
11,38,4.4,3.0,1.3,0.2,0
12,92,5.8,2.6,4.0,1.2,1
13,53,5.5,2.3,4.0,1.3,1
14,140,6.7,3.1,5.6,2.4,2
15,40,5.0,3.5,1.3,0.3,0
16,72,6.3,2.5,4.9,1.5,1
17,135,7.7,3.0,6.1,2.3,2
18,113,5.7,2.5,5.0,2.0,2
19,42,4.4,3.2,1.3,0.2,0
20,126,6.2,2.8,4.8,1.8,2
21,112,6.8,3.0,5.5,2.1,2
22,141,6.9,3.1,5.1,2.3,2
23,76,6.8,2.8,4.8,1.4,1
24,5,5.4,3.9,1.7,0.4,0
25,109,7.2,3.6,6.1,2.5,2
26,134,6.1,2.6,5.6,1.4,2
27,67,5.8,2.7,4.1,1.0,1
28,57,4.9,2.4,3.3,1.0,1
29,86,6.7,3.1,4.7,1.5,1

In [10]:
traindf = pd.read_csv("iris_train.csv")
traindf

,Unnamed: 0,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,0,5.1,3.5,1.4,0.2,0
1,1,4.9,3.0,1.4,0.2,0
2,2,4.7,3.2,1.3,0.2,0
3,4,5.0,3.6,1.4,0.2,0
4,7,5.0,3.4,1.5,0.2,0
...,...,...,...,...,...,...
115,145,6.7,3.0,5.2,2.3,2
116,146,6.3,2.5,5.0,1.9,2
117,147,6.5,3.0,5.2,2.0,2
118,148,6.2,3.4,5.4,2.3,2
119,149,5.9,3.0,5.1,1.8,2

In [11]:
test_data_list = testdf.to_numpy()[:,1:] # index 제거
test_data_list

array([[4.6, 3.2, 1.4, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5.4, 3.4, 1.5, 0.4, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [7.7, 2.6, 6.9, 2.3, 2. ],
       [5.5, 2.5, 4. , 1.3, 1. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [6.3, 2.9, 5.6, 1.8, 2. ],
       [6.7, 3.1, 4.4, 1.4, 1. ],
       [5.6, 3. , 4.1, 1.3, 1. ],
       [4.4, 3. , 1.3, 0.2, 0. ],
       [5.8, 2.6, 4. , 1.2, 1. ],
       [5.5, 2.3, 4. , 1.3, 1. ],
       [6.7, 3.1, 5.6, 2.4, 2. ],
       [5. , 3.5, 1.3, 0.3, 0. ],
       [6.3, 2.5, 4.9, 1.5, 1. ],
       [7.7, 3. , 6.1, 2.3, 2. ],
       [5.7, 2.5, 5. , 2. , 2. ],
       [4.4, 3.2, 1.3, 0.2, 0. ],
       [6.2, 2.8, 4.8, 1.8, 2. ],
       [6.8, 3. , 5.5, 2.1, 2. ],
       [6.9, 3.1, 5.1, 2.3, 2. ],
       [6.8, 2.8, 4.8, 1.4, 1. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [7.2, 3.6, 6.1, 2.5, 2. ],
       [6.1, 2.6, 5.6, 1.4, 2. ],
       [5.8, 2.7, 4.1, 1. , 1. ],
       [4.9, 2.4, 3.3, 1. , 1. ],
       [6.7, 3.1, 4.7, 1.5, 1. ]])

In [12]:
train_data_list = traindf.to_numpy()[:,1:] # index 제거
train_data_list

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.6, 0.2, 0. ],
       [4.8, 3.1, 1.6, 0.2, 0. ],
       [5.2, 4.1, 1.5, 0.1, 0. ],
       [5.5, 4.2, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5. , 3.2, 1.2, 0.2, 0. ],
       [5.5, 3.5, 1.3, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.1, 3.4, 1.5, 0.2, 0. ],
       [4.5, 2.3, 1.3, 0.3, 0. ],
       [5. , 3.5, 1.6, 0.6, 0. ],
       [5.1, 3.8, 1.9, 0.4, 0. ],
       [4.8, 3. , 1.4, 0.3, 0. ],
       [5.1, 3.8, 1.6, 0.2, 0. ],
       [5.3, 3.7, 1.5, 0.2, 0. ],
       [5. , 3.3, 1.4, 0.2, 0. ],
       [7. , 3.2, 4.7, 1.4, 1. ],
       [6.4, 3.2, 4.5, 1.5, 1. ],
       [6.9, 3.1, 4.9, 1.5, 1. ],
       [6.5, 2.8, 4.6, 1.5, 1. ],
       [5.7, 2.8, 4.5, 1.3, 1. ],
       [6.3, 3.3, 4.7, 1.6, 1. ],
       [6.6, 2.9, 4.6, 1.3, 1. ],
       [5.2, 2.7, 3.9, 1.4, 1. ],
       [5. , 2. , 3.5, 1. , 1. ],
       [5.9, 3. , 4.2, 1.5, 1. ],
       [6. , 2.2, 4. , 1. , 1. ],
       [6.1, 2.9, 4.7, 1.4, 1. ],
       [5.6, 2.9, 3.6, 1.3, 1. ],
       [5.6, 3. , 4.5, 1.5, 1. ],
       [6.2, 2.2, 4.5, 1.5, 1. ],
       [5.6, 2.5, 3.9, 1.1, 1. ],
       [5.9, 3.2, 4.8, 1.8, 1. ],
       [6.1, 2.8, 4. , 1.3, 1. ],
       [6.1, 2.8, 4.7, 1.2, 1. ],
       [6.4, 2.9, 4.3, 1.3, 1. ],
       [6.6, 3. , 4.4, 1.4, 1. ],
       [6.7, 3. , 5. , 1.7, 1. ],
       [6. , 2.9, 4.5, 1.5, 1. ],
       [5.7, 2.6, 3.5, 1. , 1. ],
       [5.5, 2.4, 3.8, 1.1, 1. ],
       [5.5, 2.4, 3.7, 1. , 1. ],
       [5.8, 2.7, 3.9, 1.2, 1. ],
       [6. , 2.7, 5.1, 1.6, 1. ],
       [5.4, 3. , 4.5, 1.5, 1. ],
       [6. , 3.4, 4.5, 1.6, 1. ],
       [6.3, 2.3, 4.4, 1.3, 1. ],
       [5.5, 2.6, 4.4, 1.2, 1. ],
       [6.1, 3. , 4.6, 1.4, 1. ],
       [5. , 2.3, 3.3, 1. , 1. ],
       [5.6, 2.7, 4.2, 1.3, 1. ],
       [5.7, 3. , 4.2, 1.2, 1. ],
       [5.7, 2.9, 4.2, 1.3, 1. ],
       [6.2, 2.9, 4.3, 1.3, 1. ],
       [5.1, 2.5, 3. , 1.1, 1. ],
       [5.7, 2.8, 4.1, 1.3, 1. ],
       [6.3, 3.3, 6. , 2.5, 2. ],
       [5.8, 2.7, 5.1, 1.9, 2. ],
       [7.1, 3. , 5.9, 2.1, 2. ],
       [6.5, 3. , 5.8, 2.2, 2. ],
       [7.6, 3. , 6.6, 2.1, 2. ],
       [4.9, 2.5, 4.5, 1.7, 2. ],
       [7.3, 2.9, 6.3, 1.8, 2. ],
       [6.7, 2.5, 5.8, 1.8, 2. ],
       [6.5, 3.2, 5.1, 2. , 2. ],
       [6.4, 2.7, 5.3, 1.9, 2. ],
       [5.8, 2.8, 5.1, 2.4, 2. ],
       [6.4, 3.2, 5.3, 2.3, 2. ],
       [6.5, 3. , 5.5, 1.8, 2. ],
       [7.7, 3.8, 6.7, 2.2, 2. ],
       [6. , 2.2, 5. , 1.5, 2. ],
       [6.9, 3.2, 5.7, 2.3, 2. ],
       [5.6, 2.8, 4.9, 2. , 2. ],
       [7.7, 2.8, 6.7, 2. , 2. ],
       [6.3, 2.7, 4.9, 1.8, 2. ],
       [6.7, 3.3, 5.7, 2.1, 2. ],
       [7.2, 3.2, 6. , 1.8, 2. ],
       [6.1, 3. , 4.9, 1.8, 2. ],
       [6.4, 2.8, 5.6, 2.1, 2. ],
       [7.2, 3. , 5.8, 1.6, 2. ],
       [7.4, 2.8, 6.1, 1.9, 2. ],
       [7.9, 3.8, 6.4, 2. , 2. ],
       [6.4, 2.8, 5.6, 2.2, 2. ],
       [6.3, 2.8, 5.1, 1.5, 2. ],
       [6.3, 3.4, 5.6, 2.4, 2. ],
       [6.4, 3.1, 5.5, 1.8, 2. ],
       [6. , 3. , 4.8, 1.8, 2. ],
       [6.9, 3.1, 5.4, 2.1, 2. ],
       [5.8, 2.7, 5.1, 1.9, 2. ],
       [6.8, 3.2, 5.9, 2.3, 2. ],
       [6.7, 3.3, 5.7, 2.5, 2. ],
       [6.7, 3. , 5.2, 2.3, 2. ],
       [6.3, 2.5, 5. , 1.9, 2. ],
       [6.5, 3. , 5.2, 2. , 2. ],
       [6.2, 3.4, 5.4, 2.3, 2. ],
       [5.9, 3. , 5.1, 1.8, 2. ]])

In [13]:
# 신경망 클래스 정의
class neuralNetwork:

    # 신경망 초기화
    def __init__(self, inodes, hnodes, onodes, lr):
        # 입력, 은닉, 출력 계층의 노드 개수 설정
        # NNlab1에서는 333, 222를 다뤘지만 각 계층의 노드 수가 다를 수도 있음
        self.inodes = inodes
        self.hnodes = hnodes
        self.onodes = onodes

        # 가중치 행렬, 행렬은 대문자로 표기
        # 배열 내 가중치는 w_ij로 표기, 노드 i에서 다음 계층의 노드 j로 연결됨
        self.W_ih = np.random.normal(0.0, pow(self.hnodes, -0.5), (self.hnodes, self.inodes))
        self.W_ho = np.random.normal(0.0, pow(self.onodes, -0.5), (self.onodes, self.hnodes))

        # 학습률
        self.lr = lr

        # 활성화 함수로는 시그모이드 함수를 이용
        self.activ_fct = lambda x: expit(x)
        pass

    # 신경망 학습시키기
    def train(self, input_list, target_list):
        # 리스트(1 x n) -> 넘파이 행렬(n x 1)
        I_i = np.array(input_list, ndmin=2).T
        T_o = np.array(target_list, ndmin=2).T

        # 은닉 계층으로 들어오는 신호
        I_h = np.dot(self.W_ih, I_i) # (주의)입력 계층에서는 I를 사용
        # 은닉 계층에서 나가는 신호
        O_h = self.activ_fct(I_h)

        # 출력 계층으로 들어오는 신호
        I_o = np.dot(self.W_ho, O_h) # 그 외 계층에서는 O를 사용
        # 출력 계층에서 나가는 신호
        O_o = self.activ_fct(I_o)

        # 출력 계층의 오차는 (실제 값 - 계산 값)
        E_o = T_o - O_o
        # 은닉 계층의 오차는
        E_h = np.dot(self.W_ho.T, E_o)

        # 은닉 계층과 출력 계층 간의 가중치 업데이트 (W = W - lr * dE/dW, dE/dW = - (t - o) * ...)
        self.W_ho += self.lr * np.dot(E_o * O_o * (1.0 - O_o), O_h.T)

        # 입력 계층과 은닉 계층 간의 가중치 업데이트
        self.W_ih += self.lr * np.dot(E_h * O_h * (1 - O_h), I_i.T)
        pass

    # 신경망에 질의하기
    def query(self, input_list):
        # 리스트(1 x n) -> 넘파이 행렬(n x 1)
        I_i = np.array(input_list, ndmin=2).T

        # 은닉 계층으로 들어오는 신호
        I_h = np.dot(self.W_ih, I_i)
        # 은닉 계층에서 나가는 신호
        O_h = self.activ_fct(I_h)

        # 출력 계층으로 들어오는 신호
        I_o = np.dot(self.W_ho, O_h)
        # 출력 계층에서 나가는 신호
        O_o = self.activ_fct(I_o)

        return O_o

In [14]:
# init
inodes = 4
hnodes = 10
onodes = 3

lr = 0.1

n = neuralNetwork(inodes, hnodes, onodes, lr)

In [15]:
# label과 data 구분
train_data_list[0]
train_data_list[0][:-1]
train_data_list[0][-1]

array([5.1, 3.5, 1.4, 0.2, 0. ])

array([5.1, 3.5, 1.4, 0.2])

0.0

In [16]:
values = np.concatenate((test_data_list[:,:-1], train_data_list[:,:-1]))
len(values)
values.max()
values.min()

150

7.9

0.1

In [17]:
# 신경망 학습시키기

# 주기(epoch)란 학습 데이터가 학습을 위해 사용되는 횟수를 의미
epochs = 300

for i in range(epochs):
    print(f"epoch {i}", end=" ")
    # 학습 데이터의 레코드를 순서대로 방문
    for row in train_data_list:
        # 입력 값의 범위와 값 조정
        inputs = np.asfarray(row[:-1]) / 7.9
        # 결과 값 생성 (실제 값인 0.99 외에는 모두 0.01)
        targets = np.zeros(onodes) + 0.1
        targets[int(row[-1])] = 0.99

        # 학습
        n.train(inputs, targets)
        pass
    print("done")
pass

epoch 0 done
epoch 1 done
epoch 2 done
epoch 3 done
epoch 4 done
epoch 5 done
epoch 6 done
epoch 7 done
epoch 8 done
epoch 9 done
epoch 10 done
epoch 11 done
epoch 12 done
epoch 13 done
epoch 14 done
epoch 15 done
epoch 16 done
epoch 17 done
epoch 18 done
epoch 19 done
epoch 20 done
epoch 21 done
epoch 22 done
epoch 23 done
epoch 24 done
epoch 25 done
epoch 26 done
epoch 27 done
epoch 28 done
epoch 29 done
epoch 30 done
epoch 31 done
epoch 32 done
epoch 33 done
epoch 34 done
epoch 35 done
epoch 36 done
epoch 37 done
epoch 38 done
epoch 39 done
epoch 40 done
epoch 41 done
epoch 42 done
epoch 43 done
epoch 44 done
epoch 45 done
epoch 46 done
epoch 47 done
epoch 48 done
epoch 49 done
epoch 50 done
epoch 51 done
epoch 52 done
epoch 53 done
epoch 54 done
epoch 55 done
epoch 56 done
epoch 57 done
epoch 58 done
epoch 59 done
epoch 60 done
epoch 61 done
epoch 62 done
epoch 63 done
epoch 64 done
epoch 65 done
epoch 66 done
epoch 67 done
epoch 68 done
epoch 69 done
epoch 70 done
epoch 71 done
epoch 72 done
epoch 73 done
epoch 74 done
epoch 75 done
epoch 76 done
epoch 77 done
epoch 78 done
epoch 79 done
epoch 80 done
epoch 81 done
epoch 82 done
epoch 83 done
epoch 84 done
epoch 85 done
epoch 86 done
epoch 87 done
epoch 88 done
epoch 89 done
epoch 90 done
epoch 91 done
epoch 92 done
epoch 93 done
epoch 94 done
epoch 95 done
epoch 96 done
epoch 97 done
epoch 98 done
epoch 99 done
epoch 100 done
epoch 101 done
epoch 102 done
epoch 103 done
epoch 104 done
epoch 105 done
epoch 106 done
epoch 107 done
epoch 108 done
epoch 109 done
epoch 110 done
epoch 111 done
epoch 112 done
epoch 113 done
epoch 114 done
epoch 115 done
epoch 116 done
epoch 117 done
epoch 118 done
epoch 119 done
epoch 120 done
epoch 121 done
epoch 122 done
epoch 123 done
epoch 124 done
epoch 125 done
epoch 126 done
epoch 127 done
epoch 128 done
epoch 129 done
epoch 130 done
epoch 131 done
epoch 132 done
epoch 133 done
epoch 134 done
epoch 135 done
epoch 136 done
epoch 137 done
epoch 138 done
epoch 139 done
epoch 140 done
epoch 141 done
epoch 142 done
epoch 143 done
epoch 144 done
epoch 145 done
epoch 146 done
epoch 147 done
epoch 148 done
epoch 149 done
epoch 150 done
epoch 151 done
epoch 152 done
epoch 153 done
epoch 154 done
epoch 155 done
epoch 156 done
epoch 157 done
epoch 158 done
epoch 159 done
epoch 160 done
epoch 161 done
epoch 162 done
epoch 163 done
epoch 164 done
epoch 165 done
epoch 166 done
epoch 167 done
epoch 168 done
epoch 169 done
epoch 170 done
epoch 171 done
epoch 172 done
epoch 173 done
epoch 174 done
epoch 175 done
epoch 176 done
epoch 177 done
epoch 178 done
epoch 179 done
epoch 180 done
epoch 181 done
epoch 182 done
epoch 183 done
epoch 184 done
epoch 185 done
epoch 186 done
epoch 187 done
epoch 188 done
epoch 189 done
epoch 190 done
epoch 191 done
epoch 192 done
epoch 193 done
epoch 194 done
epoch 195 done
epoch 196 done
epoch 197 done
epoch 198 done
epoch 199 done
epoch 200 done
epoch 201 done
epoch 202 done
epoch 203 done
epoch 204 done
epoch 205 done
epoch 206 done
epoch 207 done
epoch 208 done
epoch 209 done
epoch 210 done
epoch 211 done
epoch 212 done
epoch 213 done
epoch 214 done
epoch 215 done
epoch 216 done
epoch 217 done
epoch 218 done
epoch 219 done
epoch 220 done
epoch 221 done
epoch 222 done
epoch 223 done
epoch 224 done
epoch 225 done
epoch 226 done
epoch 227 done
epoch 228 done
epoch 229 done
epoch 230 done
epoch 231 done
epoch 232 done
epoch 233 done
epoch 234 done
epoch 235 done
epoch 236 done
epoch 237 done
epoch 238 done
epoch 239 done
epoch 240 done
epoch 241 done
epoch 242 done
epoch 243 done
epoch 244 done
epoch 245 done
epoch 246 done
epoch 247 done
epoch 248 done
epoch 249 done
epoch 250 done
epoch 251 done
epoch 252 done
epoch 253 done
epoch 254 done
epoch 255 done
epoch 256 done
epoch 257 done
epoch 258 done
epoch 259 done
epoch 260 done
epoch 261 done
epoch 262 done
epoch 263 done
epoch 264 done
epoch 265 done
epoch 266 done
epoch 267 done
epoch 268 done
epoch 269 done
epoch 270 done
epoch 271 done
epoch 272 done
epoch 273 done
epoch 274 done
epoch 275 done
epoch 276 done
epoch 277 done
epoch 278 done
epoch 279 done
epoch 280 done
epoch 281 done
epoch 282 done
epoch 283 done
epoch 284 done
epoch 285 done
epoch 286 done
epoch 287 done
epoch 288 done
epoch 289 done
epoch 290 done
epoch 291 done
epoch 292 done
epoch 293 done
epoch 294 done
epoch 295 done
epoch 296 done
epoch 297 done
epoch 298 done
epoch 299 done

In [18]:
# 신경망 테스트

# 신경망 성능의 지표가 되는 성적표를 아무 값도 가지지 않도록 초기화
scorecard = []

# 테스트 데이터의 레코드를 순서대로 방문
for row in test_data_list:
    # 정답은 index -1의 값
    correct_label = int(row[-1])
    # 입력 값의 범위와 값 조정
    inputs = np.asfarray(row[:-1]) / 7.9
    inputs
    # 신경망에 질의
    outputs = n.query(inputs)
    # 가장 높은 값의 인덱스는 레이블의 인덱스와 일치
    label = np.argmax(outputs)
    # 정답 또는 오답을 리스트에 추가
    if (label == correct_label): # 정답이면
        scorecard.append(1) # 성적표에 1을 추가
    else: # 오답이면
        scorecard.append(0) # 성적표에 0을 추가
        pass
    pass

array([0.58227848, 0.40506329, 0.17721519, 0.02531646])

array([0.58227848, 0.39240506, 0.18987342, 0.02531646])

array([0.6835443 , 0.43037975, 0.18987342, 0.05063291])

array([0.63291139, 0.37974684, 0.20253165, 0.02531646])

array([0.72151899, 0.55696203, 0.18987342, 0.05063291])

array([0.97468354, 0.32911392, 0.87341772, 0.29113924])

array([0.69620253, 0.3164557 , 0.50632911, 0.16455696])

array([0.58227848, 0.43037975, 0.17721519, 0.03797468])

array([0.79746835, 0.36708861, 0.70886076, 0.2278481 ])

array([0.84810127, 0.39240506, 0.55696203, 0.17721519])

array([0.70886076, 0.37974684, 0.51898734, 0.16455696])

array([0.55696203, 0.37974684, 0.16455696, 0.02531646])

array([0.73417722, 0.32911392, 0.50632911, 0.15189873])

array([0.69620253, 0.29113924, 0.50632911, 0.16455696])

array([0.84810127, 0.39240506, 0.70886076, 0.30379747])

array([0.63291139, 0.44303797, 0.16455696, 0.03797468])

array([0.79746835, 0.3164557 , 0.62025316, 0.18987342])

array([0.97468354, 0.37974684, 0.7721519 , 0.29113924])

array([0.72151899, 0.3164557 , 0.63291139, 0.25316456])

array([0.55696203, 0.40506329, 0.16455696, 0.02531646])

array([0.78481013, 0.35443038, 0.60759494, 0.2278481 ])

array([0.86075949, 0.37974684, 0.69620253, 0.26582278])

array([0.87341772, 0.39240506, 0.64556962, 0.29113924])

array([0.86075949, 0.35443038, 0.60759494, 0.17721519])

array([0.6835443 , 0.49367089, 0.21518987, 0.05063291])

array([0.91139241, 0.4556962 , 0.7721519 , 0.3164557 ])

array([0.7721519 , 0.32911392, 0.70886076, 0.17721519])

array([0.73417722, 0.34177215, 0.51898734, 0.12658228])

array([0.62025316, 0.30379747, 0.41772152, 0.12658228])

array([0.84810127, 0.39240506, 0.59493671, 0.18987342])

In [19]:
# 정답의 비율인 성적을 계산해 출력
scorecard_array = np.asfarray(scorecard)
scorecard_array.sum()
scorecard_array.size
print(f"hnodes = {hnodes} lr = {lr} epochs = {epochs} performance = {scorecard_array.sum() / scorecard_array.size}")

29.0

30

hnodes = 10 lr = 0.1 epochs = 300 performance = 0.9666666666666667